### ISSUE TITLE
Occasional thumbnail/image corruption

### ISSUE THREAD

**Issue by sanscriptum** [matthewn4444/Waifu2x-Image-Saver#2] opened 2017-12-13 16:27 UTC
Sometimes the thumbnail appears to be corrupted when picture gets saved (it only shows about 30/40% of it, everything else is either black or just gone), especially when picture gets scaled to 4k. It's fixable if you open it in any image editor and save it again, but that's still inconvenient. I also had a problem where photoshop refused to open scaled png file, probably because of the possible corruption.

**Comment by matthewn4444** [comment] 2017-12-13 21:11
i haven't seen the corruption before, which version are you using and if you wait a few seconds after is it still corrupted? Do you have test case example i can reproduce? As for the photoshop thing, that i've seen will fix later (waifu2xbooru force saves a png as jpg).

**Comment by sanscriptum** [comment] 2017-12-14 16:24
I'm using the latest. It's hard to pinpoint which image will get corrupted because it happens at random. I can say most often it happens when saving from pixiv or when it gets scaled to 4k as png. Sometimes it fixes itself if I wait for a few seconds, but more than often it doesn't. Maybe it's a browser thing, I've had that happen before.

Also another thing - when the saving process fails (it gets stuck indefinitely for no reason), I could start it over again and then it works fine, with latest version I cannot do it again because of the "you're saving the same image again" error.

**Comment by matthewn4444** [comment] 2017-12-14 17:56
The fixes itself after a few seconds could be because it is trying to copy the image over. What happens is I use the Firefox's Download api to download the image first then copies the upscaled image over the downloaded image to give the illusion it has been downloaded. If you double clikck the image immediately that could be the reason why it is only showing half the image (because it is still copying, are you using an ssd?).

Saving process fail, this happens once in a while pretty rare for me now, are you using Version 0.5.0c? I haven't figured out why this still happens.

Most of these issues will be fixed when I move this to a web extension model where I ditch Firefox's stupid Download api and implement my own download manager.

**Comment by sanscriptum** [comment] 2017-12-15 12:31
Nah, I leave it for a while because I download files in batches and check the folder later. It might be windows creating thumbnails from files that weren't fully downloaded at the moment yet, that's why they appear corrupted.

And yes, I'm using 0.5.0c.

**Comment by matthewn4444** [comment] 2017-12-22 07:00
Fixed in stable version of v0.5.0. Png saved from Waifubooru as jpg are converted to png as final step so you can open it in Photoshop.

**Closed as completed by matthewn4444** 2017-12-22 07:00 UTC
